SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86)

set(CROSS_PATH "/opt/gcc-android")

SET(CMAKE_C_COMPILER "${CROSS_PATH}/bin/x86-linux-android-gcc")
SET(CMAKE_CXX_COMPILER "${CROSS_PATH}/bin/x86-linux-android-g++")

SET(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
