name: Android Build

on:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  SPVC_PARAMS: -DSPIRV_CROSS_STATIC=OFF -DSPIRV_CROSS_SHARED=ON -DSPIRV_CROSS_CLI=OFF -DSPIRV_CROSS_ENABLE_TESTS=OFF -DSPIRV_CROSS_SKIP_INSTALL=ON -DSPIRV_CROSS_WERROR=OFF -DSPIRV_CROSS_FORCE_PIC=ON

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "arm", "x86", "x86_64" ]
        include:
          - arch: arm64
            triplet: aarch64-linux-android
          - arch: arm
            triplet: arm-linux-androideabi
          - arch: x86
            triplet: i686-linux-android
          - arch: x86_64
            triplet: x86_64-linux-android
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison
    - name: Install toolchain
      run: |
        wget https://github.com/MojoLauncher/gcc-toolchain/releases/download/prebuilt/gcc-13-${{matrix.arch}}-21.tar.xz -O toolchain.tar.xz 2>/dev/null
        mkdir gcc
        tar xf toolchain.tar.xz -C gcc
        mv gcc /opt/gcc-android
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../gcc-${{matrix.arch}}.cmake $SPVC_PARAMS
        make -j$(nproc)
        /opt/gcc-android/bin/${{matrix.triplet}}-strip libspirv-cross-c-shared.so
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: spvc-${{matrix.arch}}
        path: build/libspirv-cross-c-shared.so

  aar:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get packaging script
      uses: actions/checkout@v6
      with:
        repository: 'MojoLauncher/mesaunified-packager'
    - name: Install zip
      run: sudo apt -y install zip unzip
    - name: Get spvc arm64
      uses: actions/download-artifact@v4
      with:
        name: spvc-arm64
        path: spvc/arm64
    - name: Get spvc arm
      uses: actions/download-artifact@v4
      with:
        name: spvc-arm
        path: spvc/arm
    - name: Get spv x86
      uses: actions/download-artifact@v4
      with:
        name: spvc-x86
        path: spvc/x86
    - name: Get spvc x86_64
      uses: actions/download-artifact@v4
      with:
        name: spvc-x86_64
        path: spvc/x86_64
    - name: Pack AAR
      run: bash create_aar.sh $GITHUB_WORKSPACE/spvc spvc
    - name: Upload packaging result
      uses: actions/upload-artifact@v7
      with:
        name: spvc-aar
        path: spvc.aar
        
        
      
    
